### ISSUE TITLE
Issues with using prior and plotting

### ISSUE THREAD

**Issue by bioinfonm** [goldingn/GRaF#6] opened 2016-03-04 02:20 UTC
Hello,

  We are using GRaF for a project and we have some priors we are trying out.

When I run this code I get a dims do not match error.

`thresh_tuna <- function(x) ifelse(graf.df$anntempmea < 10, 0.2, 0.6)`
`> m2_graf
GRaF model fitted with
   2630 presence records
   320 absence records
   and 6 covariates
> m2_graf$l
[1] 5.322097 6.107969 8.059627 7.998849 7.535967 6.607742
> par(mfrow = c(1, 6))
> plot(m2_graf,prior=TRUE)
Error in pred(newdata, object, mn, std = TRUE, maxn = maxn) : 
  dims [product 50] do not match the length of object [2950]`

I am not quite sure other then I think the graf object is not matching the dataframe.

Thanks!
ara

**Comment by goldingn** [comment] 2016-03-04 20:36
Hi Ara,

Great that you're trying out GRaF, and I'm happy to help where I can!

I'm afraid I can't do much to work out what's wring without an example I can run at my end. I'm not asking for all your data and code, but if you were able to replicate the error with a small fake dataset and code, I could work out what's up. I appreciate that isn't always easy with this sort of problem though.

Guessing from those error messages though, it looks like new data either isn't a dataframe or doesn't have the same covariate columns (same number, order and exactly the same names)?

Thus package doesn't have as much handling of incorrect inputs as I'd like, but I think the docs are explicit about what each function expects. Assuming that is the case?

Nick

**Comment by bioinfonm** [comment] 2016-03-04 20:59
Nick,

  Thanks for the response. What strikes me as weird is that I can run it without the prior just fine for both the 2D and 3D plots. Let me see if I can wrangle my R script and data into a format I can post here. 

ara

**Comment by bioinfonm** [comment] 2016-03-04 21:12
Nick,
  
  Here is my data as a csv and the R script I am currently using. In the main script we start from a gridded shapefile and use fortify to convert the data to a dataframe. 

ara

[graf_test.txt.zip](https://github.com/goldingn/GRaF/files/159389/graf_test.txt.zip)
[graf_test_script.R.zip](https://github.com/goldingn/GRaF/files/159390/graf_test_script.R.zip)

**Comment by goldingn** [comment] 2016-03-04 21:25
Thanks Ara! It's the weekend here now and I only have my phone, so will take a look next week and get back to you.

**Comment by goldingn** [comment] 2016-03-10 04:04
Hi Ara,

Sorry for the delay, I forgot I had a training course at the start of this week which sapped all of my time.

I've just taken a look and there are two things going on here:

Firstly your mean function is accessing the dataframe `graf.df` in the global environment, rather than the one passed to the function. I.e. you have:
```r
thresh_shark <- function(x) ifelse(graf.df$anntempmea < 15, 0.2, 0.6)
```
but it should instead be:
```r
thresh_shark <- function(x) ifelse(x$anntempmea < 15, 0.2, 0.6)
```
So it fits the model OK, but when it tries to predict to a sequence of data for plotting the vecotrs suddenly don't line up. R's unusual lexical scoping rules ("if I can't see this variable here, look in the parent environment, then the one above that") mean that this is expected behaviour, but it trips me up *so* often.

However, fixing this leads us to the following error:
```r
m2_graf <- graf(pres_abs, covs_richness, method = c('Laplace'), prior = thresh_shark)
```
```
Error in K %*% b : non-conformable arguments
```
The reason for this is that the variable `anntempmea` isn't in the selected covariates dataframe: `covs_richness`. It didn't trip up before, because it was finding it in that other dataframe. Unfortunately `graf` can only deal with a mean function which acts on the same covariates as the GP. Adding this covariate to the dataframe fixes the problem:

```r
covs_richness <- graf.df[, c("meantempme","meanlognpp","chlorlogme",
                             "ETOPO1mean","logcoast","proxmean", "anntempmea")]
```

Sorry this didn't get picked up by any checks, or provide more informative warning messages. It's nigh-on impossible to anticipate and check user-written functions!

I'll close this now, but feel free to re-open or file a new issue if it doesn't work for you.

And I'm really pleased you're using the method and playing with priors - get in touch if you have any more questions!

**Comment by bioinfonm** [comment] 2016-03-22 13:53
Ah! Thanks for the catches. I was switching between different dataframes and column names. It runs perfect now. 

Thanks!
ara

**Closed** 2016-03-30 02:41 UTC
